### ISSUE TITLE
ユーザーごとに覚えさせたものを返すコマンド

### ISSUE THREAD

**Issue by kabo2468** [kabo2468/oishii-bot#23]
ex.
/getuser (userId)
でその人が覚えさせたものを返すコマンド

**Comment by nenohi** [comment]
userId部分は@nenohi@misskey.io形式とは別な方が良さそう？

**Comment by kabo2468** [comment]
メンションが行くと困るときがあるのでそれじゃないほうがいいかな

**Comment by nenohi** [comment]
管理者用だからuser:nenohi instance:misskey.ioとかでも許されそう

**Comment by kabo2468** [comment]
インスタンスごとにuserIdっていうのがあって、ユニークユーザーごとに割り当てられてるから、それ使うのがいいかも
(例えばioから`7saao1wsup`は`@kabo@misskey.io`)
